# Generated by Django 4.0 on 2022-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parquejkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plazas',
            old_name='idplazas',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='ususariok',
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
